//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Tinkerbell Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Boots) DeepCopyInto(out *Boots) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Boots.
func (in *Boots) DeepCopy() *Boots {
	if in == nil {
		return nil
	}
	out := new(Boots)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hegel) DeepCopyInto(out *Hegel) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hegel.
func (in *Hegel) DeepCopy() *Hegel {
	if in == nil {
		return nil
	}
	out := new(Hegel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rufio) DeepCopyInto(out *Rufio) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rufio.
func (in *Rufio) DeepCopy() *Rufio {
	if in == nil {
		return nil
	}
	out := new(Rufio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TinkServer) DeepCopyInto(out *TinkServer) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TinkServer.
func (in *TinkServer) DeepCopy() *TinkServer {
	if in == nil {
		return nil
	}
	out := new(TinkServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tinkerbell) DeepCopyInto(out *Tinkerbell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tinkerbell.
func (in *Tinkerbell) DeepCopy() *Tinkerbell {
	if in == nil {
		return nil
	}
	out := new(Tinkerbell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tinkerbell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TinkerbellSpec) DeepCopyInto(out *TinkerbellSpec) {
	*out = *in
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Boots = in.Boots
	out.Hegel = in.Hegel
	out.Rufio = in.Rufio
	out.TinkServer = in.TinkServer
	out.TinkController = in.TinkController
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TinkerbellSpec.
func (in *TinkerbellSpec) DeepCopy() *TinkerbellSpec {
	if in == nil {
		return nil
	}
	out := new(TinkerbellSpec)
	in.DeepCopyInto(out)
	return out
}
